services:
    signed.security.authentication.provider:
        class: Dendy\SignedAuthBundle\Security\Authentication\Provider\SignedAuthProvider
        arguments: ["@logger", "", ""]
        public: false
    signed.security.authentication.listener:
        class: Dendy\SignedAuthBundle\Security\Firewall\SignedAuthListener
        arguments: ["@security.token_storage", "@security.authentication.manager", ""]
        public: false
